### ISSUE TITLE
Pushover: No dynamic messaging / environment variables in text

### ISSUE THREAD

**Issue by cstuder** [maddox/actions#10]
When sending a push notification via the GitHub action `maddox/actions/pushover@master` I would like to send a dynamic message including the commit SHA (`GITHUB_SHA`) or the ref (`GITHUB_REF`).

Currently this is not possible since the message is hardcoded in the environment variables of the action itself. Indirect expansion (I.E. `${!GITHUB_SHA}`) doesn't work either.

This could be solved by not using environment variables to transmit the message, but pass the message in the `args` parameter.

Requires a rewrite of the action, but might be done backward compatible. I.e. if the named argument `title` is not passed in `args`, take the enviroment variable `TITLE` instead.

**Comment by cstuder** [comment]
Note before you invest too much time into this: I got sucked down the rabbit hole of GitHub actions and developed my own notification action here: https://github.com/cstuder/apprise-ga

You can close this issue if you want.

**Comment by maddox** [comment]
Oh cool! I wasn't aware of that tool. That seems awesome.

**Comment by cstuder** [comment]
It is. :-)
