### ISSUE TITLE
GitHub SSH Key

### ISSUE THREAD

**Issue by spiray** [maddox/actions#15]
@maddox I have a node project that has a GitHub repo as a dependency. When I run `npm install` in Actions I get the error saying that the host key is invalid as it tries to access it via ssh. Would this action be applicable to my use case? What would the HOST, USER, and PRIVATE_KEY be? If not, would you know what I can do to fix that?

**Comment by klitynski** [comment]
@spiray how did you resolve?

**Comment by spiray** [comment]
@klitynski I realized I was using this action incorrectly. I just set up an ssh key by getting it from a GCP bucket and copying it in. Ultimately I went down a completely different route but that is how I resolved that.
