### ISSUE TITLE
Error: Docker build failed with exit code 100

### ISSUE THREAD

**Issue by Noitidart** [maddox/actions#19]
When using the ssh action I'm getting this error:

```
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
  The command '/bin/sh -c apt-get update && apt-get install -y   openssh-client &&   rm -Rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

Does this action need to be updated?

**Comment by elvismdev** [comment]
Same issue here, @Noitidart were you able to figure out?

**Comment by maddox** [comment]
These actions were built against the gen1 version of GitHub Actions. I would expect them to not work.

**Comment by fxamauri** [comment]
any solution for this problem?

**Comment by fxamauri** [comment]
https://github.com/debuerreotype/docker-debian-artifacts/issues/135

**Comment by Noitidart** [comment]
> Same issue here, @Noitidart were you able to figure out?

I couldn't figure it out so switched to https://github.com/JimCronqvist/action-ssh/ - is there another ssh action anyone reocmmends?

**Comment by fxamauri** [comment]
Guys, the problem has been solved, they have updated the official debian:stable-slim image in the docker repository solving the problem.
