### ISSUE TITLE
Maybe replace "/github/home" with "$HOME"?

### ISSUE THREAD

**Issue by anishkny** [maddox/actions#3]
Loving these little actions, I see them being so useful (once I get access ☹️ haha)

Perhaps this does not need to be hardcoded:

https://github.com/maddox/actions/blob/fdde19760a32663c4a1f257e0ba10b1d2768d5f4/ssh/entrypoint.sh#L5

how about:

```bash
SSH_PATH="$HOME/.ssh"
```

GitHub seems to set `HOME=/github/home`. See [here](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#environment-variables).

**Comment by maddox** [comment]
Resolved in #4
